services:
  frontend:
    build:
      context: . # thư mục chứa Dockerfile và React code
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "80:80" # truy cập http://localhost:5173
    restart: always

    env_file:
      - .env.docker
    networks:
      - phpadmin_my_network

networks:
  phpadmin_my_network:
    external: true
